### ISSUE TITLE
[Question] Patch for AA for custom apps

### ISSUE THREAD

**Issue by aleksgeko** [jilleb/mib2-toolbox#158]
Hello! Congratulations for what you created.
I used your tool and is excellent!

I want to patch gal.json to create mirrorlink(Android Auto custom apps patch) to my MIB2 but without @MIB2-toolbox. 
Can you help me please with an idea to do this? 
I see this file but i want to do this just via command in putty and sdcard. 
Sorry if is stupid my question.

**Comment by jilleb** [comment]
Thanks!

It's not a stupid question at all 😎
If you want to edit the gal.json file, make sure you have mounted the app volume as rewriteable:

`mount -uw /mnt/app`

On the mmx console.

Then, you can edit the file manually with vi, but... vi is not nice to work with if you're not really familiar with it.
So you can copy the file to sd-card, edit it offline on your laptop and cp it back to the original location, and restart the unit.


If you look into the toolbox scripts find the one that patches the android auto config. Inside it you see a bunch of commands that are used to replace the contents in gal.json (all the lines with "sed"), there you can see the pattern it looks for and the pattern it's putting instead.

I'm currently not near my pc and replying from mobile, otherwise I could have easily copy pasted the right commands, but can't currently 😅 is this enough to get you on your way?

**Comment by aleksgeko** [comment]
Thank you very much for your quickly reply.
Sorry if i have little experience in this, but, can you help me please with commands and file to can patch this? 
Thank you very much!

**Comment by aleksgeko** [comment]
Because i want to learn much more how work this. Is just for me, i like to learn this and i want to try this.

**Comment by olli991** [comment]
All commands you need are in the according scripts. If you want to lean it then I guess you should adapt and try what is in there. 

If we just write you the finished commands then there is no leaning involved. Everything you need is in the script for AA patch.

**Comment by aleksgeko** [comment]
Ok Olli, i will try with this script to do this. Thank you very much, i will be back here if something is not working. Thanks and i'm your sponsor for this work. If maybe i can help, i'm here for your team. Thanks!!!

**Comment by olli991** [comment]
If you have question on specific parts of the script we can help of course. But all you need is in the script ;-)
