### ISSUE TITLE
[BUG]  MIB2 fails to start after half year of installing mib2-toolbox

### ISSUE THREAD

**Issue by newlocal42** [jilleb/mib2-toolbox#173]
After installing the Carplay/AAuto features everything goes well. After about half a year the MIB2 failed to boot and stops at "Initialising Audi smartphone interface". No keypress accepted and reboots in about 2 minutes. After reboot, everything starts again and fail again the same way.

 - Brand: Audi A6 4G 2016
 - Hardware-type MIB2
 - Version K3663

It is a very familiar problem to some other programming problems when storage gets full and no space left for temporary files and the program crashes.

It seems like the MIB2 internal storage gets full after a half-year of everyday usage. 

Please check your scripts running in the MIB2 after every reboot. Maybe that is the cause of filling up the internal storage. Also, it would be great to know how to reset the MIB2 unit to get the control-buttons working to install an updated version of mib2-toolbox.

**Comment by jilleb** [comment]
I've got it running for 3 years on my development device and in my own car for 2.5 years without issues... There's nothing happening during the boot, which has been changed by the toolbox, so that shouldn't be it. The toolbox does not run anything on the device when you don't call it from the green menu.

Can you explain what you mean by the Carplay features you've installed? That doesn't sound familiar, the toolbox has no Carplay features.

**Comment by newlocal42** [comment]
I'm really sorry about this report. It was meant to go mibsolution.eu. There is no bug in your code. I installed both and mixed up the bugs.

**Comment by jilleb** [comment]
Lol, no problem.
