### ISSUE TITLE
Android Auto custom apps, how does it work?

### ISSUE THREAD

**Issue by oOEnergyOo** [jilleb/mib2-toolbox#254]
Hi!

After patching my unit with the M.I.B tool for carplay and lifetime updates, I installed the toolbox (v.4.1a) and performed a full backup. After this I started the script "Android Auto custom apps patch", and at the end it was written being all successful. I did a reset, plugged in the phone, but it was all as before. Just the few apps like maps, spotify and whatapp were available.

MHI2_ER_AU37x_P5089

That´s my gal.json file after running the script.
[gal.json.txt](https://github.com/jilleb/mib2-toolbox/files/12388416/gal.json.txt)

Any ideas what´s the problem here?

**Comment by jilleb** [comment]
You need to have an older version of Android Auto to be able to use this feature, because Google disabled custom apps after people started running YouTube clients in their cars. And even then, you need apps that are AA enabled, it doesn't give you access to all the apps on your Android Auto.

However, using AAAD (Android Auto App Downloader) probably still allows you to run custom apps.
