### ISSUE TITLE
Metainfo2.txt error

### ISSUE THREAD

**Issue by yanqemil** [jilleb/mib2-toolbox#4]
Skoda Kodiaq Columbus not work, not with v2.0....same error metainfo2.txt
![20190920_192528](https://user-images.githubusercontent.com/55596599/65375405-e915b180-dc9d-11e9-8f2f-29fa5812f278.jpg)
 Y try with sdcard formated exfat and usbstick formated fat32. All files correct extracted in sdcard/stick 🙁 same error.

**Comment by yanqemil** [comment]
My Columbus
![20190921_183816](https://user-images.githubusercontent.com/55596599/65375516-49f1b980-dc9f-11e9-9a21-d32ea1ff8ad2.jpg)
 is version sw 1240, code 565035021 B

**Comment by dirk3012** [comment]
Same problem

**Comment by jilleb** [comment]
@dirk3011, please specify your firmware version.

**Comment by dchrisd** [comment]
@jilleb i tried out the new version from you (V2) but same problem with metainfo2.txt error like in V1.4 and V1.6


brand: Seat
part nr.: 5F0035043F
hw version: 5F0035043
sw train version: mhi2_er_seg11_p4517
sw mu version: 1219
software version: h29.319.43_high2_eu

maybe you can send me please the firmware, so that i can update the unit to 1433 and try it again :D

**Comment by dirk3012** [comment]
5NA035042D Firmware 1367

**Comment by dirk3012** [comment]
brand: VW
part nr.: 5NA035042D
hw version: 5NA035042
sw train version: mhi2_er_vwg13_p4521
sw mu version: 1367
software version: h29.319.75_high2gp_eu

**Comment by jilleb** [comment]
VW 1367 is a confirmed working firmware version with the toolkit. I'm using it myself to develop and test it.... So there must be something else that's causing the issue. We can rule out firmware version as a cause in your case. It has to be a difference in the way the files are on your SD card and on mine. The zip file is the exact same as what I'm running myself. 


Seat firmware I can check. I'm not opposed to sharing firmware, but it's best to PM me on Facebook about this.

**Comment by dirk3012** [comment]
it was previously a 5NA035042A Firmware 1161 . I have the firmware 1367 on it about 5 months on it. Everything is fine.

**Comment by jilleb** [comment]
Let's look at this in a more analytical way:

- if it's installing and working on multiple units with the sae firmware version, but it doesn't work on your unit with the same firmware version: the problem is not in the toolbox, because it's proven to work in others with the same situation. We need to look at "what's different" between your case and other people's situation. In my experience, this has almost always something to do with bad copy/paste work, slow SD-cards, 
- if it's not working on your firmware version, and other people are having troubles with this same version as well: the problem is with the toolbox not being supported by the firmware.

The toolbox is installed through a "feature" in the SWDL-function (software download/upgrade mechanisme in MIB2), and if a certain firmware gives errors, it's most probable that it's because this "feature" is not there. Upgrade to the most recent version for your brand/model and try again.

**Comment by dirk3012** [comment]
I tried 3 different sd cards. Fat32, Fat, NTFS. and 2 different USB sticks including Fat32 and Ntfs. I do not know what I'm doing wrong.

**Comment by jilleb** [comment]
Don't use usb, use SD card

**Comment by jilleb** [comment]
This is a duplicate from issue #1
