### ISSUE TITLE
Can't Read Metainfo2.txt

### ISSUE THREAD

**Issue by Sensei1978** [jilleb/mib2-toolbox#87]
Hi.
I have a patched MIB2High Discover Pro.
The FW Version is 0687.
3G0035021D.

When i will install the mib2toolbox it always comes the errormessage that the DP can't read the metainfo2.txt

**Comment by DamoRSS** [comment]
Hi, Thanks for all the hard work that has been put into this! Unfortunately i am getting the same Metainfo2.txt error. I have used my macbook pro to move the files to a 2GB micro sd (in a sd adapter) but i am unable to progress any further :( I am going to try a few things including using a windows PC to copy files over instead of Mac but if you have any pointers please let me know @jilleb i have also attached a few pictures of my headunit info incase i am missing some compatibility issue?? 
Thanks
D
![WhatsApp Image 2020-08-25 at 11 01 33](https://user-images.githubusercontent.com/33870859/91161362-94a35f00-e6c2-11ea-8663-149bb577b2df.jpeg)
![WhatsApp Image 2020-08-25 at 11 01 44](https://user-images.githubusercontent.com/33870859/91161365-966d2280-e6c2-11ea-89e8-5a20f4b57685.jpeg)

**Comment by jilleb** [comment]
Duplicate from #49 

Patched units could provide some issues, because I don't know what the patchers did to ifsroot and if it causes troubles.
