### ISSUE TITLE
[BUG] Enabling Dev Mode from shell

### ISSUE THREAD

**Issue by CaneTLOTW** [jilleb/mib2-toolbox#98]
I tried to use the shell command to enable dev mode on my Skoda Columbus MIB2.5 unit.
I can run the command, but dev mode is not enabled (also after reboot).

I used dumb_persistence_reader and confirm, that 00 is changed to 01.
It seems to be the wrong place. I would like to help, but do not understand (yet) how the adressing is done...

**Comment by andy0172** [comment]
This command is working on Skoda MIB2.5:
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production
on -f mmx  /net/mmx/eso/bin/dumb_persistence_writer -P 0 3221356557 01

**Comment by CaneTLOTW** [comment]
That is the one I tried...

**Comment by jilleb** [comment]
After this you need to reset with persistence... Otherwise it will not save the command.

mib2_ioc_flash reboot


or

Run this script to request reset with persistence.

`#!/bin/ksh
#shell script to request an rset with persistence

echo "request reset with persistence"
sleep 2
mount -uw /mnt/system
touch /etc/ooc.allow.reset
echo hmi-sys-reset > /dev/ooc/reset
sleep 2
rm /etc/ooc.allow.reset
echo "request send"
`

**Comment by jilleb** [comment]
This became a bit obsolete, toolbox is now enabling dev mode during install
